'use client';

import type {Metadata} from 'next';
import {Geist, Geist_Mono} from 'next/font/google';
import './globals.css';
import Link from 'next/link';
import {Toaster} from '@/components/ui/toaster';
import {auth} from '@/lib/firebase';
import {useEffect, useState} from 'react';
import {signOut} from 'firebase/auth';

// export const metadata: Metadata = {
//   title: 'OpenChat.Ai',
//   description: 'Generated by Firebase Studio',
// };

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const [user, setUser] = useState<any>(null);

  useEffect(() => {
    if (auth) {
      const unsubscribe = auth.onAuthStateChanged(
        authUser => {
          if (authUser) {
            setUser({
              uid: authUser.uid,
              email: authUser.email,
            });
          } else {
            setUser(null);
          }
        },
        error => {
          console.error('Error during auth state change:', error);
        }
      );

      return () => unsubscribe();
    }
  }, []);

  const handleSignOut = async () => {
    try {
      await signOut(auth);
      setUser(null);
    } catch (error) {
      console.error('Sign out failed:', error);
    }
  };

  return (
    <html lang="en">
      <head>
        <title>OpenChat.Ai</title>
        <meta name="description" content="Generated by Firebase Studio" />
      </head>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <nav className="p-4 border-b">
          <div className="container mx-auto flex justify-between items-center">
            <Link href="/" className="text-2xl font-bold">OpenChat.Ai</Link>
            <div>
              {user ? (
                <>
                  <span className="mr-4">
                    {user.email}
                  </span>
                  <Link href="/" onClick={handleSignOut}>
                    Sign Out
                  </Link>
                </>
              ) : (
                <>
                  <Link href="/login" className="mr-4">Login</Link>
                  <Link href="/signup">Sign Up</Link>
                </>
              )}
            </div>
          </div>
        </nav>
        {children}
        <Toaster />
      </body>
    </html>
  );
}
